services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8000:8000"

  order-service:
    build:
      context: ./order-service
    ports:
      - "8001:8000"
    depends_on:
      - user-service
      - payment-service

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8002:8000"
    depends_on:
      - user-service
