apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
type: Opaque
data:
  DB_HOST: ZGF0YWJhc2UtbWljcm9zZXJ2aWNlcy5jYzdpdThncWtud2wudXMtZWFzdC0xLnJkcy5hbWF6b25h
  DB_USER: d3MuY29t
  DB_PASS: VnJ2Q0JrN2JBdGZXa0E4cTlLd0s=
  DB_NAME: ZGF0YWJhc2UtbWljcm9zZXJ2aWNlcw==
