name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the pipeline on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 717279687729.dkr.ecr.us-east-1.amazonaws.com/user-service:latest

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update this with your region

      - name: Deploy to EKS
        uses: aws-actions/eks-update-kubeconfig@v2
        with:
          cluster-name: microservices-cluster
          region: us-east-1

      - name: Deploy using kubectl
        run: |
          kubectl apply -f k8s/user-deployment.yaml
          kubectl apply -f k8s/order-deployment.yaml
          kubectl apply -f k8s/payment-deployment.yaml
